spring:
  cache:
    cache-names: tpc-cache
  datasource:
    url: jdbc:mysql://ecloud-db-mysql:3306/ecloud_tpc?characterEncoding=utf8&useSSL=false

liquibase:
  change-log: classpath:liquibase/index.xml
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  url: ${spring.datasource.url}

mybatis:
  type-aliases-package: com.ecloud.provider.model.domain
  mapper-locations: classpath:mapper/*.xml,classpath*:sdk/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: com.ecloud.core.mybatis.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

security:
  oauth2:
    client:
      clientId: ecloud-client-mdc
      clientSecret: ecloudClientSecret
      access-token-uri: http://ecloud-gateway:7979/uac/oauth/token
      user-authorization-uri: http://ecloud-gateway:7979/uac/oauth/authorize
    resource:
      user-info-uri: http://ecloud-gateway:7979/uac/user
      prefer-token-info: false
      jwt:
        key-uri: http://ecloud-provider-uac:8000/oauth/token_key

ecloud:
  enableSqlLogInterceptor: false
  dingTalk:
    webhookToken:
      jobListener: 7b0fcc73f3d2be1415c5d31e5b34100c689961454af15a61635749ba0d8*****
  token:
    interceptor:
      enable: true
  message:
    maxSendTimes: 7
    handleTimeout: 5
    resendMultiplier: 2
  aliyun:
    rocketMq:
      enable: false
      reliableMessageConsumer: false
      reliableMessageProducer: true
      namesrvAddr: ecloud-mq-rocket:9876
      instanceName: ecloud-provider-tpc
      producerGroup: PID_TPC
  oauth2:
    jwtSigningKey: ecloud
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUrl: ${security.oauth2.client.access-token-uri}
      clientId: ${security.oauth2.client.clientId}
      clientSecret: ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header
      tokenStore: jwt
  zk:
    zkAddressList: ecloud-provider-zk:2181
    namespace: ecloud-elastic-job
  job:
    task:
      dingTalk:
        cron: 0 0/20 * * * ?
        shardingTotalCount: 1
        shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
      sendingMessage:
        cron: 0 0/20 * * * ?
        shardingTotalCount: 1
        jobParameter: fetchNum=200,taskType=SENDING_MESSAGE
      waitingMessage:
        cron: 0 0/20 * * * ?
        shardingTotalCount: 1
        jobParameter: fetchNum=200,taskType=WAITING_MESSAGE

dataflowJob:
  cron: 0 */20 * * * ?
  shardingTotalCount: 1
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou